# Generated by Django 2.2 on 2020-06-22 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200620_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 16, 40, 35, 263548), verbose_name='Expire le'),
        ),
    ]
