# Generated by Django 2.2 on 2020-06-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200623_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 22, 9, 26, 808109), verbose_name='Expire le'),
        ),
    ]
