# Generated by Django 2.2 on 2020-06-30 16:51

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20200630_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 16, 51, 30, 23080), verbose_name='Expire le'),
        ),
    ]
