# Generated by Django 2.2 on 2020-07-04 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20200630_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='besoinsemis',
            options={'managed': True, 'verbose_name': 'Beneficiaire', 'verbose_name_plural': 'Beneficiaires'},
        ),
        migrations.AlterField(
            model_name='apporteraide',
            name='montantApporte',
            field=models.IntegerField(blank=True, choices=[(46, '$46'), (91, '$91'), (182, '$182'), (364, '$364'), (455, '$455'), (728, '$728'), (910, '$910')], null=True, verbose_name='Montant Apporté'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 53, 0, 9525), verbose_name='Expire le'),
        ),
    ]
