# Generated by Django 2.2 on 2020-07-04 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20200704_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 55, 40, 64322), verbose_name='Expire le'),
        ),
    ]
