# Generated by Django 2.2 on 2020-07-05 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20200704_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apporteraide',
            name='montantApporte',
            field=models.IntegerField(blank=True, choices=[(46, '46,00 $US'), (91, '91,00 $US'), (182, '182,00 $US'), (364, '364,00 $US'), (455, '455,00 $US'), (728, '728,00 $US'), (910, '910,00 $US')], null=True, verbose_name='Montant Apporté'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pays',
            field=models.CharField(blank=True, choices=[('South Africa', 'South Africa'), ('Algérie', 'Algérie'), ('Allemagne', 'Allemagne'), ('Australia', 'Australia'), ('Angola', 'Angola'), ('Belgique', 'Belgique'), ('Benin', 'Benin'), ('Botswana', 'Botswana'), ('Brazilia', 'Brazilia'), ('Burkina Faso', 'Burkina Faso'), ('Canada', 'Canada'), ('Cameroun', 'Cameroun'), ('RD Congo', 'RD Congo'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Damemark', 'Damemark'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinéé', 'Guinéé'), ('Israel', 'Israel'), ('Mali', 'Mali'), ('Maroc', 'Maroc'), ('Nigeria', 'Nigeria'), ('Niger', 'Niger'), ('Togo', 'Togo'), ('Tunisia', 'Tunisia'), ('USA', 'USA')], max_length=25, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='souscriptions',
            name='dateDexpiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 11, 29, 29, 451569), verbose_name='Expire le'),
        ),
    ]
