# Generated by Django 2.2 on 2020-06-22 16:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='url',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='url'),
        ),
    ]
