# Generated by Django 2.2 on 2020-06-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infos', '0002_informations_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='url',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='url'),
        ),
    ]
