# Generated by Django 2.2 on 2020-06-28 22:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infos', '0003_auto_20200623_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nom')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('objet', models.CharField(blank=True, max_length=256, null=True, verbose_name='Objet')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contacts',
                'managed': True,
            },
        ),
    ]
